CREATE TABLE Bruker (
    Epost VARCHAR(255) NOT NULL,
    Fornavn VARCHAR(255),
    Etternavn VARCHAR(255),
    Passord VARCHAR(255),
    CONSTRAINT Bruker_PK PRIMARY KEY (Epost)
);

CREATE TABLE Brenneri (
    ID INTEGER NOT NULL,
    Navn VARCHAR(255),
    CONSTRAINT Brenneri_PK PRIMARY KEY (ID)
);

CREATE TABLE Gård (
    ID INTEGER NOT NULL,
    HoydeOverHavet INTEGER,
    Land VARCHAR(255),
    Region VARCHAR(255),
    Navn VARCHAR(255),
    CONSTRAINT Gård_PK PRIMARY KEY (ID)
);

CREATE TABLE Kaffebønne (
    Art VARCHAR(255) NOT NULL,
    CONSTRAINT Kaffebønne_PK PRIMARY KEY (Art)
);

CREATE TABLE Foredlingsmetode (
    Navn VARCHAR(255) NOT NULL,
    Beskrivelse VARCHAR(255),
    CONSTRAINT Foredlingsmetode_PK PRIMARY KEY (Navn)
);

CREATE TABLE Kaffeparti (
    ID INTEGER NOT NULL,
    GårdID INTEGER NOT NULL,
    ForedlingsmetodeNavn VARCHAR(255) NOT NULL,
    Innhøstningsår INTEGER,
    BetaltPerKiloUSD REAL,
    CONSTRAINT Kaffeparti_PK PRIMARY KEY (ID),
    CONSTRAINT Kaffeparti_FK1 FOREIGN KEY (GårdID) REFERENCES Gård(ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT Kaffeparti_FK2 FOREIGN KEY (ForedlingsmetodeNavn) REFERENCES Foredlingsmetode (Navn) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE BønneIParti (
    Art VARCHAR(255) NOT NULL,
    PartiID INTEGER NOT NULL,
    CONSTRAINT BønneIParti_PK PRIMARY KEY (Art, PartiID),
    CONSTRAINT BønneIParti_FK1 FOREIGN KEY (Art) REFERENCES Kaffebønne (Art) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT BønneIParti_FK2 FOREIGN KEY (PartiID) REFERENCES Kaffeparti (ID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Kaffe (
    ID INTEGER NOT NULL,
    PartiID INTEGER NOT NULL,
    BrenneriID INTEGER NOT NULL,
    Brenningsgrad VARCHAR(255),
    Navn VARCHAR(255),
    Beskrivelse VARCHAR(255),
    Brenningsdato VARCHAR(255),
    KiloprisNOK REAL,
    CONSTRAINT Kaffe_PK PRIMARY KEY (ID),
    CONSTRAINT Kaffe_FK1 FOREIGN KEY (PartiID) REFERENCES Kaffeparti(ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT Kaffe_FK2 FOREIGN KEY (BrenneriID) REFERENCES Brenneri(ID) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE Kaffesmaking (
    ID INTEGER NOT NULL,
    BrukerEpost VARCHAR(255) NOT NULL,
    KaffeID INTEGER NOT NULL,
    Smaksdato VARCHAR(255),
    Score INTEGER,
    Smaksnotater VARCHAR(255),
    CONSTRAINT Kaffesmaking_PK PRIMARY KEY (ID),
    CONSTRAINT Kaffesmaking_FK1 FOREIGN KEY (BrukerEpost) REFERENCES Bruker(Epost) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT Kaffesmaking_FK2 FOREIGN KEY (KaffeID) REFERENCES Kaffe(ID) ON UPDATE CASCADE ON DELETE RESTRICT
);